# Generated by Django 6.0.5 on 2026-05-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_workshopcategory_portfolioimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopprofile',
            name='categories',
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
        migrations.DeleteModel(
            name='WorkshopCategory',
        ),
    ]
