# Generated by Django 6.0.5 on 2026-05-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_portfolioimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'ordering': ['-is_pinned', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
