# Generated by Django 6.0.5 on 2026-05-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_category_workshopprofile_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopprofile',
            name='categories',
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, to='workshop.category'),
        ),
    ]
