# Generated by Django 5.2.14 on 2026-05-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0014_workshopdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopdetail',
            name='active_orders',
        ),
        migrations.RemoveField(
            model_name='workshopdetail',
            name='item_drop_off',
        ),
        migrations.RemoveField(
            model_name='workshopdetail',
            name='response_time',
        ),
    ]
