# Generated by Django 5.2.14 on 2026-05-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_request_category_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In review'), ('time_ended', 'Time ended'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
