# Generated by Django 5.2.14 on 2026-05-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_ai_refine_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestimage',
            name='caption',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
