# Generated by Django 5.2.14 on 2026-05-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_merge_20260512_2232'),
        ('account', '0007_merge_20260513_0824'),
    ]

    operations = [
    ]
