# Generated by Django 5.2.14 on 2026-05-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_merge_20260513_1818'),
        ('account', '0011_merge_20260513_2029'),
    ]

    operations = [
    ]
