# Generated by Django 6.0.5 on 2026-05-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_merge_20260513_2027'),
        ('account', '0013_alter_artisanprofile_id_alter_profile_id_and_more'),
    ]

    operations = [
    ]
