# Generated by Django 6.0.5 on 2026-05-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_merge_20260514_0911'),
        ('account', '0014_merge_20260514_0835'),
    ]

    operations = [
    ]
