# Generated by Django 6.0.5 on 2026-05-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_artisanprofile_id_alter_profile_id_and_more'),
        ('account', '0015_merge_20260514_1141'),
    ]

    operations = [
    ]
