# Generated by Django 5.2.14 on 2026-05-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_merge_20260517_2104'),
        ('account', '0019_artisanprofile_stripe_connected_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanprofile',
            name='avatar',
            field=models.ImageField(default='images/avatars/default_avatar.png', upload_to='images/avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/avatars/default_avatar.png', upload_to='images/avatars/'),
        ),
    ]
